FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app/api
COPY otel-demo.csproj .
RUN dotnet restore 
COPY . .
RUN dotnet publish -c Release -o out

#Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/api/out .
ENTRYPOINT ["dotnet", "otel-demo.dll"]