---
apiVersion: v1
kind: Namespace
metadata:
  name: azure-alb-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: azure-alb
  namespace: flux-system
spec:
  interval: 1m0s
  url: oci://mcr.microsoft.com/helm/application-lb
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-alb-add-on
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: azure-alb-system
  chart:
    spec:
      chart: alb-controller
      version: '1.4.14'
      sourceRef:
        kind: HelmRepository
        name: azure-alb
        namespace: flux-system
      interval: 1m
  values:
    albController:
      namespace: azure-alb-system
      podIdentity:
        clientID: 481da86a-20b9-49b0-a521-206104485d2f