#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: crossplane-system
#---
#apiVersion: source.toolkit.fluxcd.io/v1beta1
#kind: HelmRepository
#metadata:
#  name: crossplane-stable
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  url: https://charts.crossplane.io/stable
#---
#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: crossplane
#  namespace: flux-system
#spec:
#  interval: 5m
#  targetNamespace: crossplane-system
#  chart:
#    spec:
#      chart: crossplane
#      version: '1.10.2'
#      sourceRef:
#        kind: HelmRepository
#        name: crossplane-stable
#        namespace: flux-system
#      interval: 1m
---
apiVersion: v1
kind: Namespace
metadata:
  name: upbound-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: upbound-stable
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.upbound.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: upbound
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: upbound-system
  chart:
    spec:
      chart: universal-crossplane
      version: 'v1.10.2-up.1'
      sourceRef:
        kind: HelmRepository
        name: upbound-stable
        namespace: flux-system
      interval: 1m

  
  