version: '3'

env:
  TITLE: AKS Automatic Demo
  DEFAULT_REGION: "westus3"

tasks:
  default:
    cmds:
    - task --list
    
  up:
    desc: Creates a complete {{.TITLE}} environment 
    cmds:
    - task: init
    - task: apply
    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  init:
    cmds: 
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  apply:
    cmds:
    - terraform apply -auto-approve -var "region={{.REGION}}" -var "tags={{.TITLE}}" -compact-warnings
    - task: creds
    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  creds:
    desc: Gets AKS credential file
    cmds:
    - az aks get-credentials -g {{.RG}} -n {{.AKS}} --overwrite-existing
    - sed -i s/devicecode/azurecli/g ~/.kube/config
    vars:
      RG: 
        sh: terraform output -raw RESOURCE_GROUP
      AKS: 
        sh: terraform output -raw AKS_CLUSTER_NAME

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group list --tag Application="{{.TITLE}}" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --verbose --no-wait -n || true
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true
    vars:
      RG: 
        sh: terraform  output -raw RESOURCE_GROUP
