version: '3'

vars:
  SKU: "Standard_D4s_v5"
  COUNT: 5
  TAG:  Azure Container Storage Demo
  DEFAULT_REGION: canadaeast
  
tasks:
  up:
    desc: Creates a {{.TAG}} environment 
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    - task: apply
    - task: creds
    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  plan:
    desc: Compile required Terraform states and plan for deployment 
    cmds:
    - terraform plan -var "region={{.REGION}}" -var "vm_size={{.SKU}}" -var "node_count={{.COUNT}}" -compact-warnings
    vars: 
      REGION: '{{default "" .CLI_ARGS}}'

  apply:
    desc: Creates the Environment 
    cmds:
    - terraform apply -auto-approve 
      -var "region={{.REGION}}"
      -var "vm_size={{.SKU}}"
      -var "node_count={{.COUNT}}" 
      -var "tags={{.TAG}}"

    vars: 
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  creds:
    desc: Gets AKS credential file
    cmds:
    - az aks get-credentials -g {{.RG}} -n {{.AKS}} --overwrite-existing
    - sed -i s/devicecode/azurecli/g ~/.kube/config
    vars:
      RG: 
        sh: terraform output -raw AKS_RESOURCE_GROUP
      AKS: 
        sh: terraform output -raw AKS_CLUSTER_NAME

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group list --tag Application={{.TAG}} --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --verbose --no-wait -n  || true
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
