FROM mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-ltsc2022 AS build-env
WORKDIR /src

USER Administrator

COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -r win-x64 --self-contained --nologo -o publish/windows  

FROM mcr.microsoft.com/dotnet/runtime:8.0-nanoserver-ltsc2022
WORKDIR /app
COPY --from=build-env /src/publish/windows .
EXPOSE 5000
ENTRYPOINT ["/app/otel-prometheus"]