global using Microsoft.Extensions.DependencyInjection;
global using Azure.Monitor.OpenTelemetry.AspNetCore;
global using OpenTelemetry.Metrics;
global using OpenTelemetry.Trace;
global using OpenTelemetry.Logs;
global using OpenTelemetry.Resources;
global using System.Diagnostics.Metrics;
global using System.Diagnostics;
global using Microsoft.AspNetCore.Mvc;