apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver0
spec:
    serviceName: mssqlsvc0
    replicas: 1
    selector:
      matchLabels:
        app: sqlserver0
    template:
      metadata:
        labels: 
          app: sqlserver0
      spec:
        terminationGracePeriodSeconds: 10
        initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R 775 /var/opt/mssql']
          volumeMounts:
          - name: mssql-pv-claim
            mountPath: /var/opt/mssql
        containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
          ports:
          - containerPort: 1433
          env:
          - name: MSSQL_ENABLE_HADR
            value: '1'
          - name: MSSQL_DATA_DIR
            value: "/var/opt/mssql/data"
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: 'Y'
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql 
                key: SA_PASSWORD 
          volumeMounts:
            - name: mssql-pv-claim
              mountPath: /var/opt/mssql
          securityContext:
            runAsUser: 10001 
            runAsGroup: 0
        volumes:
        - name: mssql-pv-claim
          persistentVolumeClaim:
            claimName: azure-managed-disk0
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver1
spec:
    serviceName: mssqlsvc1
    replicas: 1
    selector:
      matchLabels:
        app: sqlserver1
    template:
      metadata:
        labels: 
          app: sqlserver1
      spec:
        terminationGracePeriodSeconds: 10
        initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R 775 /var/opt/mssql']
          volumeMounts:
          - name: mssql-pv-claim
            mountPath: /var/opt/mssql
        containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
          ports:
          - containerPort: 1433
          - containerPort: 5022
          env:
          - name: MSSQL_ENABLE_HADR
            value: '1'
          - name: MSSQL_DATA_DIR
            value: "/var/opt/mssql/data"
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: 'Y'
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql 
                key: SA_PASSWORD 
          volumeMounts:
            - name: mssql-pv-claim
              mountPath: /var/opt/mssql
          securityContext:
            runAsUser: 10001 
            runAsGroup: 0
        volumes:
        - name: mssql-pv-claim
          persistentVolumeClaim:
            claimName: azure-managed-disk1
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlsvc0
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels: 
   app: sqlserver0
spec:
  selector:
    app: sqlserver0
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
    name: sqlserver
  - port: 5022
    targetPort: 5022
    protocol: TCP
    name: sqlserver-ag
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlsvc1
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels: 
   app: sqlserver1
spec:
  selector:
    app: sqlserver1
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
    name: sqlserver
  - port: 5022
    targetPort: 5022
    protocol: TCP
    name: sqlserver-ag
  type: LoadBalancer