---
apiVersion: v1
kind: Namespace
metadata:
  name: vela-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kubevela
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.kubevela.net/core
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vela
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: vela-system
  chart:
    spec:
      chart: vela-core
      version: '1.7.2'
      sourceRef:
        kind: HelmRepository
        name: kubevela
        namespace: flux-system
      interval: 1m