version: '3'

dotenv: 
  - .env

vars:
  TITLE: Private Azure Redhat OpenShift with User Define Routes demo
  DEFAULT_REGION: canadaeast
  DEFAULT_DOMAIN: bjdazure.tech
  CLUSTER_VERSION: 4.18.26
   

tasks:
  default:
    cmds:
    - task --list
    
  up:
    desc: Creates {{.TITLE}} environment
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    - task: apply
    - task: creds
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}' 

  apply:
    desc: Applies Terraform configuration
    cmds:
    - terraform apply -auto-approve -compact-warnings
      -var "tags={{.TITLE}}" 
      -var "region={{.REGION}}" 
      -var "domain={{.DEFAULT_DOMAIN}}"
      -var "cluster_version={{.CLUSTER_VERSION}}"
      -var "host_encryption_enabled=false"
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}' 

  refresh:
    desc: Refresh a Terraform configuration and outputs
    cmds:
    - terraform refresh
      -var "tags={{.TITLE}}" 
      -var "region={{.REGION}}" 
      -var "domain={{.DEFAULT_DOMAIN}}"
      -var "cluster_version={{.CLUSTER_VERSION}}"
    vars:
      REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}' 

  creds:
    desc: Get ARO Credentials
    cmds:
    - az aro list-credentials --name {{.ARO_NAME}} --resource-group {{.RG}}
    vars:
      RG: 
        sh: terraform output -raw RESOURCE_GROUP  
      ARO_NAME: 
        sh: terraform output -raw ARO_NAME  

  down:
    desc: Destorys Azure infrastructure and cleans up terraform state files
    cmds:
    - rm -rf .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info terraform.tfstate.d || true
    - az group delete -n {{.RG}} --yes --no-wait || true
    vars:
      RG: 
        sh: terraform output -raw RESOURCE_GROUP
