#FROM alpine:3.16.5
FROM alpine:3.18.3

RUN apk add --update \
    python3 \
    python3-dev \
    py3-pip \
    py3-setuptools \
    build-base \
    py3-cffi 

RUN pip3 install -U pip 
RUN pip3 install gunicorn httpbin 

RUN echo '#!/bin/sh' > run.sh \
    && echo 'gunicorn --bind=0.0.0.0:8080 httpbin:app' >> run.sh \
    && chmod +x run.sh 

RUN rm -rf /var/cache/apk/* \
    && apk del python3-dev 

EXPOSE 8080
CMD ["./run.sh"]
