---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-demo-svc
  namespace: {{ .Values.NAMESPACE }}
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: prometheus-demo
  ports:
  - port: 80
    targetPort: {{ .Values.SERVICE_PORT }}
    name: web
  - port: 9090
    targetPort: 9090
    name: metrics
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtheus-demo
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: prometheus-demo
        azure.workload.identity/use: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      containers:
      - name: prometheus-demo
        image: {{ print .Values.ACR.NAME "/otel-demo/" .Values.CONTAINER_NAME ":" .Values.GIT_COMMIT_VERSION }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.SERVICE_PORT }}
        - containerPort: 9090
        env:
        - name: APP_INSIGHTS_CONNECTION_STRING
          value: {{ .Values.APP_INSIGHTS.CONNECTION_STRING }}
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "64Mi"
            cpu: "0.25"                   
{{- if .Values.DEPLOY_ON.WINDOWS }}         
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: role
        operator: Equal
        value: applications
        effect: NoSchedule 
{{- end }}  